#Upload data

In [1]:
# 本機執行版:原範本此格為 Colab 掛載 Google Drive,本機不需要
print('local run - skip Colab drive mount')

local run - skip Colab drive mount

In [2]:
import pandas as pd 
df= pd.read_csv('Assessment 2a Cellphone-1.csv') 
df.head()

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0,128,1,1,2.7,1,265.1,110,89.0,9.87,10.0
1,0,107,1,1,3.7,1,161.6,123,82.0,9.78,13.7
2,0,137,1,0,0.0,0,243.4,114,52.0,6.06,12.2
3,0,84,0,0,0.0,2,299.4,71,57.0,3.10,6.6
4,0,75,0,0,0.0,3,166.7,113,41.0,7.42,10.1

Calculating summary statistics of inputs

In [3]:
df.describe()

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,0.144914,101.064806,0.903090,0.276628,0.816475,1.562856,179.775098,100.435644,56.305161,10.051488,10.237294
std,0.352067,39.822106,0.295879,0.447398,1.272668,1.315491,54.467389,20.069084,16.426032,2.535712,2.791840
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,0.000000
25%,0.000000,74.000000,1.000000,0.000000,0.000000,1.000000,143.700000,87.000000,45.000000,8.330000,8.500000
50%,0.000000,101.000000,1.000000,0.000000,0.000000,1.000000,179.400000,101.000000,53.500000,10.070000,10.300000
75%,0.000000,127.000000,1.000000,1.000000,1.780000,2.000000,216.400000,114.000000,66.200000,11.770000,12.100000
max,1.000000,243.000000,1.000000,1.000000,5.400000,9.000000,350.800000,165.000000,111.300000,18.190000,20.000000

**Call 6 classifiers libraries **

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

Call classifiers performance metrics libraries

In [5]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
import numpy as np

**collecting all the input features**

In [6]:
df_feature = df.drop(['Churn'], axis=1)
df_feature.head()
df_feature.describe()

,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,0.903090,0.276628,0.816475,1.562856,179.775098,100.435644,56.305161,10.051488,10.237294
std,39.822106,0.295879,0.447398,1.272668,1.315491,54.467389,20.069084,16.426032,2.535712,2.791840
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,0.000000
25%,74.000000,1.000000,0.000000,0.000000,1.000000,143.700000,87.000000,45.000000,8.330000,8.500000
50%,101.000000,1.000000,0.000000,0.000000,1.000000,179.400000,101.000000,53.500000,10.070000,10.300000
75%,127.000000,1.000000,1.000000,1.780000,2.000000,216.400000,114.000000,66.200000,11.770000,12.100000
max,243.000000,1.000000,1.000000,5.400000,9.000000,350.800000,165.000000,111.300000,18.190000,20.000000

In [7]:
df_feature.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccountWeeks     3333 non-null   int64
 1   ContractRenewal  3333 non-null   int64
 2   DataPlan         3333 non-null   int64
 3   DataUsage        3333 non-null   float64
 4   CustServCalls    3333 non-null   int64
 5   DayMins          3333 non-null   float64
 6   DayCalls         3333 non-null   int64
 7   MonthlyCharge    3333 non-null   float64
 8   OverageFee       3333 non-null   float64
 9   RoamMins         3333 non-null   float64
dtypes: float64(5), int64(5)
memory usage: 260.5 KB

**Examining dependent (output) feature**

In [8]:
df_label = df['Churn']
df_label.head()

0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64

Calculating the summary statistics of output feature

In [9]:
df_label.describe()

count    3333.000000
mean        0.144914
std         0.352067
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Churn, dtype: float64

**Preparing train and test data**

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df_feature, df_label, test_size=0.3)

**Finding the accuracy of RandomForest model **

In [11]:
model = RandomForestClassifier()
# fit the model
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy * 100)
print(classification_report(y_test,y_pred))

93.5
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       846
           1       0.89      0.66      0.76       154

    accuracy                           0.94      1000
   macro avg       0.92      0.82      0.86      1000
weighted avg       0.93      0.94      0.93      1000

**Finding the importance of varibles per RandomForest model**

In [12]:
model = RandomForestClassifier()
# fit the model
model.fit(X_train, y_train)
# get importance
importance = model.feature_importances_

# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.06358
Feature: 1, Score: 0.06429
Feature: 2, Score: 0.01860
Feature: 3, Score: 0.07761
Feature: 4, Score: 0.14258
Feature: 5, Score: 0.19354
Feature: 6, Score: 0.07010
Feature: 7, Score: 0.16280
Feature: 8, Score: 0.12004
Feature: 9, Score: 0.08686

**Finding the importance of varibles per XGB model**

In [13]:
model = XGBClassifier()
# fit the model
model.fit(X_train, y_train)
# get importance
importance = model.feature_importances_

# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.02848
Feature: 1, Score: 0.25808
Feature: 2, Score: 0.11612
Feature: 3, Score: 0.08707
Feature: 4, Score: 0.18328
Feature: 5, Score: 0.10007
Feature: 6, Score: 0.03307
Feature: 7, Score: 0.08792
Feature: 8, Score: 0.05373
Feature: 9, Score: 0.05217

**Finding the importance of varibles per DecisionTree & Logistic Regression model**

In [14]:
model = DecisionTreeClassifier()
# fit the model
model.fit(X_train, y_train)
# get importance
importance = model.feature_importances_

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy * 100)
print(classification_report(y_test,y_pred))

# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

90.0
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       846
           1       0.68      0.66      0.67       154

    accuracy                           0.90      1000
   macro avg       0.81      0.80      0.81      1000
weighted avg       0.90      0.90      0.90      1000

Feature: 0, Score: 0.04465
Feature: 1, Score: 0.06706
Feature: 2, Score: 0.00000
Feature: 3, Score: 0.07795
Feature: 4, Score: 0.13108
Feature: 5, Score: 0.21393
Feature: 6, Score: 0.04697
Feature: 7, Score: 0.15242
Feature: 8, Score: 0.15224
Feature: 9, Score: 0.11370

In [15]:
model = LogisticRegression()
# fit the model
model.fit(X_train, y_train)
# get importance
importance = model.coef_[0]

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy * 100)
print(classification_report(y_test,y_pred))

# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

85.1
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       846
           1       0.55      0.17      0.26       154

    accuracy                           0.85      1000
   macro avg       0.71      0.57      0.59      1000
weighted avg       0.82      0.85      0.82      1000

Feature: 0, Score: -0.00378
Feature: 1, Score: -2.29588
Feature: 2, Score: -0.21221
Feature: 3, Score: 0.04280
Feature: 4, Score: 0.45678
Feature: 5, Score: 0.01232
Feature: 6, Score: -0.00874
Feature: 7, Score: -0.02530
Feature: 8, Score: 0.06179
Feature: 9, Score: -0.01112

/Users/pokaihuang/Desktop/KennyPriv/UTS_workspace/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Notice that the coefficients are both positive and negative. The positive scores indicate a feature that predicts class 1, whereas the negative scores indicate a feature that predicts class 0.

*Calculating the Confusion matrix

In [16]:
confusion_matrix(y_test, y_pred)

array([[825,  21],
       [128,  26]])

*Calculating the number of False Negative outcomes

In [17]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

In [18]:
tn, fp, fn, tp

(np.int64(825), np.int64(21), np.int64(128), np.int64(26))